### PR TITLE
Jio bug 1460051

### PR DESCRIPTION
**Pull request by sajuptpm**
Closes-bug: https://bugs.launchpad.net/jio/+bug/1460051

### CODE REVIEW

**Comment by hkumarmk** [comment]
I think this should be part of puppet-rjil, the code going in puppet-neutron should be reusable everywhere, so any rjil/jiocloud specific code should be in puppet-rjil.

**Comment by sajuptpm** [comment]
@hkumarmk Patch moved to https://github.com/JioCloud/puppet-rjil/pull/625

**Comment by hkumarmk** [comment]
@sajuptpm so we can close this PR right?

**Comment by sajuptpm** [comment]
Yes, we can close it.

**Pull request closed without merging**
